### 📝 Login (Đăng nhập & Lưu token tự động)
POST http://localhost:8080/api/transactions/login
Content-Type: application/json

{
  "accountNumber": "11111",
  "pin": "555555"
}

> {% client.global.set("authToken", response.body.token); %}

###

### 📝 Withdraw (Rút tiền)
POST http://localhost:8080/api/transactions/withdraw
Authorization: Bearer {{authToken}}  // Thay <your_generated_jwt_token> bằng {{authToken}} nếu bạn dùng Postman
Content-Type: application/json

{
  "amount": 50000000
}
###

### 📝 Withdraw with OTP (Rút tiền qua OTP)
POST http://localhost:8080/api/transactions/send-otp
Content-Type: application/json

{
  "accountNumber": "11111"
}

###
POST http://localhost:8080/api/transactions/process-with-otp
Content-Type: application/json

{
  "accountNumber": "11111",
  "amount": 50,
  "otp": "123456"
}

####

###
### 📝 Nạp tiền (Rút tiền)
POST http://localhost:8080/api/transactions/deposit
Authorization: Bearer {{authToken}}  // Thay <your_generated_jwt_token> bằng {{authToken}} nếu bạn dùng Postman
Content-Type: application/json

{
  "amount": 500000000
}
###

### 📝 Chuyển tiền (Rút tiền)
POST http://localhost:8080/api/transactions/transfer
Authorization: Bearer {{authToken}}  // Thay <your_generated_jwt_token> bằng {{authToken}} nếu bạn dùng Postman
Content-Type: application/json

{
  "amount": 500000,
  "targetAccountNumber": "0000000000"
}
###

# 📝 Get Balance (Kiểm tra số dư)
GET http://localhost:8080/accounts/balance
Authorization: Bearer {{authToken}}

###

### 📝 Get Transaction History (Lấy lịch sử giao dịch)
GET http://localhost:8080/api/transactions/history
Authorization: Bearer {{authToken}}
Content-Type: application/json


###

### 📝 Logout (Đăng xuất)
POST http://localhost:8080/api/transactions/logout
Authorization: Bearer {{authToken}}
